# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beverage', models.CharField(max_length=10)),
                ('sugars', models.IntegerField(default=0)),
                ('milk', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
