# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuppa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='brew',
            name='milkiness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuppa.Tea'),
        ),
    ]
